# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  # - name: Articles
  #   url: articles/
  #   weight: 30

