# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Articles
    url: articles/
    weight: 20
  - name: Topics
    url: tags/
    weight: 30

